
services:

  broker:
    image: eclipse-mosquitto
    container_name: roundabout_mqttbroker
    ports:
      - "${PORT_LOCAL_BROKER}:${PORT_BROKER}"                       # Expose port so you can watch traffic from your host machine
      - "${PORT_LOCAL_BROKER_WEBSOCKET}:${PORT_BROKER_WEBSOCKET}"   # Optional: for WebSockets if you use a web visualizer
    volumes:
      - ./service-mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - broker-network

  controller:
    build:
      context: .
      dockerfile: service-controller/Dockerfile
    container_name: roundabout-controller
    depends_on:
      - broker
    env_file:
      - .env
    ports:
      - "${PORT_LOCAL_CONTROLLER}:${PORT_CONTROLLER}"
    networks:
      - broker-network

  vehicle:
    build:
      context: .
      dockerfile: service-vehicle/Dockerfile
    depends_on:
      - broker
    env_file:
    - bash-scripts/clean.env.generated
    deploy:
      replicas: 20 #10
    networks:
      - broker-network

  webviewer:
    build:
      context: .
      dockerfile: service-webviewer/Dockerfile
    container_name: roundabout-viewer
    depends_on:
      - broker
    env_file:
      - .env
    ports:
      - "${PORT_LOCAL_WEBVIEWER}:${PORT_WEBVIEWER}"
    networks:
      - broker-network


networks:
  broker-network:
    driver: bridge
