
services:

  broker:
    image: eclipse-mosquitto
    container_name: roundabout_mqttbroker
    # expose PORT_BROKER if you need to watch traffic from your host machine
    # optional PORT_BROKER_WEBSOCKET: for WebSockets if you use a web visualizer
    volumes:
      - ./service-mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - broker-network

  controller:
    build:
      context: .
      dockerfile: service-controller/Dockerfile
    container_name: roundabout-controller
    depends_on:
      - broker
    env_file:
      - bash-scripts/clean.env.generated
    networks:
      - broker-network

  simulation:
    build:
      context: .
      dockerfile: service-simulation/Dockerfile
    container_name: roundabout-simulation
    depends_on:
      - broker
    env_file:
      - bash-scripts/clean.env.generated
    networks:
      - broker-network

  vehicle:
    build:
      context: .
      dockerfile: service-vehicle/Dockerfile
    depends_on:
      - broker
    env_file:
      - bash-scripts/clean.env.generated
    deploy:
      replicas: ${VEHICLE_REPLICA_N}
    networks:
      - broker-network

  webviewer:
    build:
      context: .
      dockerfile: service-webviewer/Dockerfile
    container_name: roundabout-viewer
    depends_on:
      - broker
    env_file:
      - bash-scripts/clean.env.generated
    ports:
      - "${PORT_LOCAL_WEBVIEWER}:${PORT_WEBVIEWER}"
    networks:
      - broker-network


networks:
  broker-network:
    driver: bridge
